[
  {
    "b_id"      : "AA1000",
    "root_no"   : "A01",
    "s_location": "colombo",
    "s_time"    : "12.00",
    "desti"     : "kandy",
    "arrTime"   : "5.00",
    "sp1"       : "Peliyagoda",
    "sp1t"      : "1.00",
    "sp2"       : "gampaha",
    "sp2t"      : "2.00",
    "sp3"       : "Nittambuwa",
    "sp3t"      : "2.,30",
    "sp4"       : "Kegalle",
    "sp4t"      : "3.40",
    "sp5"       : "Mawanella",
    "sp5t"      : "4.00",
    "sp6"       : "Peradeniya",
    "sp6t"      : "4.45"
  },
  {
    "b_id"      : "AA2000",
    "root_no"   : "A02",
    "s_location": "colombo",
    "s_time"    : "12.00",
    "desti"     : "mathara",
    "arrTime"   : "5.00",
    "sp1"       : "Panadura",
    "sp1t"      : "1.30",
    "sp2"       : "kaluthara",
    "sp2t"      : "2.00",
    "sp3"       : "Aluthgama",
    "sp3t"      : "2.45",
    "sp4"       : "Ambalangoda",
    "sp4t"      : "3.30",
    "sp5"       : "galle",
    "sp5t"      : "4.00",
    "sp6"       : "place1",
    "sp6t"      : "4.20"
  },
  {
    
    "b_id"      : "AA2000",
    "root_no"   : "A02",
    "s_location": "galle",
    "s_time"    : "11.00",
    "desti"     : "mathara",
    "arrTime"   : "5.00",
    "sp1"       : "Panadura",
    "sp1t"      : "1.30",
    "sp2"       : "kaluthara",
    "sp2t"      : "2.00",
    "sp3"       : "Aluthgama",
    "sp3t"      : "2.45",
    "sp4"       : "Ambalangoda",
    "sp4t"      : "3.30",
    "sp5"       : "galle",
    "sp5t"      : "4.00",
    "sp6"       : "place1",
    "sp6t"      : "4.20"
  }
]
